version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: webapp_dev
      POSTGRES_HOST_AUTH_METHOD: trust

  backend:
    depends_on:
      - postgres
    build: .
    command: pnpm start:docker
    ports:
      - 3000:3000
      - 9229:9229 # for debugging
    environment:
      DATABASE_URL: postgres://postgres@postgres/webapp_dev
      PORT: 3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.pnpm-store
