version: '3.9'
services:
  backend:
    build: .
    ports:
      - 3000:3000
      - 9229:9229 # for debugging
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.pnpm-store
    command: pnpm start:docker
    environment:
      PORT: 3000
